# Build settings
markdown: kramdown
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "The Diary of a Young Black Woman"
description: > # this means to ignore newlines until "email:"
   Live, learn, love

email: youngblackwoman@gmail.com
#blog logo
logo: "/assets/images/my_logo.jpg"
# blog cover
cover: "/assets/images/download.jpg"

name: 'Young Black Woman'
author: 'Young Black Woman'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://thediaryofayoungblackwoman.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@yungblackwoman'

#fill in disqus shortname to use disqus
disqus: youngblackwoman

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/yungblackwoman
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:
    desc: 
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	instagram
    url:	https://instagram.com/yungblackwoman
    desc:	Follow me on Instagram
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
